use super::bc_table::BcTable;
use super::constants::constants_struct;
use super::coupled_common::{
    base_assembly_items, coefficient_value_expr, coupled_offsets, coupled_unknown_components,
};
use super::dsl as typed;
use super::state_access::state_component_slot;
use super::wgsl_ast::{
    AccessMode, AssignOp, Attribute, Block, Expr, Function, Item, Module, Param, Stmt, Type,
};
use super::wgsl_bindings::{storage_var, uniform_var, vector2_struct};
use super::wgsl_dsl as dsl;
use super::KernelWgsl;
use crate::solver::codegen::coupled_common::kernel_bindings_from_items;
use crate::solver::codegen::ir::{DiscreteOpKind, DiscreteSystem};
use crate::solver::codegen::primitive_expr::resolve_field_refs;

use crate::solver::gpu::enums::GpuBcKind;
use crate::solver::ir::ports::{ParamSpec, ResolvedStateSlotsSpec};
use crate::solver::ir::{Discretization, DispatchDomain, KernelProgram, LaunchSemantics};

const GENERIC_COUPLED_WORKGROUP_SIZE: u32 = 64;

pub fn generate_generic_coupled_assembly_wgsl(
    system: &DiscreteSystem,
    slots: &ResolvedStateSlotsSpec,
    needs_gradients: bool,
    eos_params: &[ParamSpec],
) -> KernelWgsl {
    let coupled_stride = coupled_unknown_components(system).len() as u32;

    struct Dispatch<'a> {
        system: &'a DiscreteSystem,
        slots: &'a ResolvedStateSlotsSpec,
        needs_gradients: bool,
        eos_params: &'a [ParamSpec],
    }
    impl typed::DispatchByStride<KernelWgsl> for Dispatch<'_> {
        fn call<Ax: typed::CoupledAxis>(&self) -> KernelWgsl {
            let mut module = Module::new();
            module.push(Item::Comment(
                "GENERATED BY CFD2 CODEGEN (generic_coupled_assembly)".to_string(),
            ));
            module.push(Item::Comment("DO NOT EDIT MANUALLY".to_string()));
            module.extend(base_assembly_items(
                self.needs_gradients,
                false,
                self.eos_params,
            ));
            module.push(Item::Function(main_assembly_fn::<Ax>(
                self.system,
                self.slots,
            )));
            KernelWgsl::from(module)
        }
    }
    typed::dispatch_by_coupled_stride(
        coupled_stride,
        Dispatch {
            system,
            slots,
            needs_gradients,
            eos_params,
        },
    )
    .unwrap_or_else(|e| panic!("{e}"))
}

pub fn generate_generic_coupled_update_wgsl(
    system: &DiscreteSystem,
    slots: &ResolvedStateSlotsSpec,
    primitives: &[(u32, Expr)],
    apply_relaxation: bool,
    relaxation_requires_dtau: bool,
    eos_params: &[ParamSpec],
) -> KernelWgsl {
    let mut module = Module::new();
    module.push(Item::Comment(
        "GENERATED BY CFD2 CODEGEN (generic_coupled_update)".to_string(),
    ));
    module.push(Item::Comment("DO NOT EDIT MANUALLY".to_string()));
    module.extend(base_update_items(eos_params));
    module.push(Item::Function(main_update_fn(
        system,
        slots,
        primitives,
        apply_relaxation,
        relaxation_requires_dtau,
    )));
    KernelWgsl::from(module)
}

pub fn generate_generic_coupled_update_kernel_program(
    id: &str,
    system: &DiscreteSystem,
    slots: &ResolvedStateSlotsSpec,
    primitives: &[(u32, Expr)],
    apply_relaxation: bool,
    relaxation_requires_dtau: bool,
    eos_params: &[ParamSpec],
) -> Result<KernelProgram, String> {
    let items = base_update_items(eos_params);
    let bindings = kernel_bindings_from_items(&items)?;
    let main = main_update_fn(
        system,
        slots,
        primitives,
        apply_relaxation,
        relaxation_requires_dtau,
    );
    let (launch, consumed_stmts) = launch_from_update_statements(&main.body.stmts)?;
    let kernel_stmts = &main.body.stmts[consumed_stmts..];

    let mut program = KernelProgram::new(id, DispatchDomain::Cells, launch, bindings);
    program.indexing = vec![cfd2_ir::ast::Stmt::Let {
        name: "base".to_string(),
        ty: None,
        expr: cfd2_ir::ast::Expr::ident("idx") * cfd2_ir::ast::Expr::lit_u32(slots.stride as u32),
    }];
    program.body = kernel_stmts.to_vec();
    program.eos_params = eos_params.to_vec();
    Ok(program)
}

pub fn generate_generic_coupled_apply_wgsl(eos_params: &[ParamSpec]) -> KernelWgsl {
    let mut module = Module::new();
    module.push(Item::Comment(
        "GENERATED BY CFD2 CODEGEN (generic_coupled_apply)".to_string(),
    ));
    module.push(Item::Comment("DO NOT EDIT MANUALLY".to_string()));
    module.extend(base_apply_items(eos_params));
    module.push(Item::Function(main_apply_fn()));
    KernelWgsl::from(module)
}

pub fn generate_generic_coupled_apply_kernel_program(
    id: &str,
    eos_params: &[ParamSpec],
) -> Result<KernelProgram, String> {
    let items = base_apply_items(eos_params);
    let bindings = kernel_bindings_from_items(&items)?;
    // Build the apply function using `idx` as the index variable directly,
    // matching the KernelProgram lowerer's convention (`let idx = ...`).
    let main = main_apply_fn_with_index_var("idx");

    // The apply function uses:
    //   stmt 0: let idx = global_id.y * constants.stride_x + global_id.x   (launch index)
    //   stmt 1: let n = arrayLength(&row_offsets) - 1u                      (bounds value)
    //   stmt 2: if (idx >= n) { return; }                                   (bounds guard)
    //   stmts 3..: body
    let idx_expr = match main.body.stmts.first() {
        Some(Stmt::Let { expr, .. }) => expr.to_string(),
        _ => {
            return Err(
                "generic_coupled_apply: expected first statement to define idx launch expression"
                    .to_string(),
            );
        }
    };
    let bounds_expr = match main.body.stmts.get(1) {
        Some(Stmt::Let { expr, .. }) => expr.to_string(),
        _ => {
            return Err(
                "generic_coupled_apply: expected second statement to define n bounds".to_string(),
            );
        }
    };

    let launch = LaunchSemantics::new(
        [GENERIC_COUPLED_WORKGROUP_SIZE, 1, 1],
        idx_expr,
        Some(format!("idx >= ({bounds_expr})")),
    );

    let kernel_stmts = &main.body.stmts[3..];

    let mut program = KernelProgram::new(id, DispatchDomain::Cells, launch, bindings);
    program.body = kernel_stmts.to_vec();
    program.eos_params = eos_params.to_vec();
    Ok(program)
}

fn launch_from_update_statements(stmts: &[Stmt]) -> Result<(LaunchSemantics, usize), String> {
    let idx_expr = match stmts.first() {
        Some(Stmt::Let { name, expr, .. }) if name == "idx" => expr.to_string(),
        _ => {
            return Err(
                "generic_coupled_update: expected first statement to define idx launch expression"
                    .to_string(),
            );
        }
    };

    let num_cells_expr = match stmts.get(1) {
        Some(Stmt::Let { name, expr, .. }) if name == "num_cells" => expr.to_string(),
        _ => {
            return Err(
                "generic_coupled_update: expected second statement to define num_cells".to_string(),
            );
        }
    };

    match stmts.get(2) {
        Some(Stmt::If {
            then_block,
            else_block,
            ..
        }) if else_block.is_none()
            && then_block.stmts.len() == 1
            && matches!(then_block.stmts.first(), Some(Stmt::Return(None))) => {}
        _ => {
            return Err(
                "generic_coupled_update: expected third statement to be idx bounds guard"
                    .to_string(),
            );
        }
    }

    Ok((
        LaunchSemantics::new(
            [GENERIC_COUPLED_WORKGROUP_SIZE, 1, 1],
            idx_expr,
            Some(format!("idx >= ({num_cells_expr})")),
        ),
        3,
    ))
}

fn base_update_items(eos_params: &[ParamSpec]) -> Vec<Item> {
    vec![
        Item::Struct(vector2_struct()),
        Item::Struct(constants_struct(eos_params)),
        Item::Comment("Group 0: Fields".to_string()),
        storage_var("state", Type::array(Type::F32), 0, 0, AccessMode::ReadWrite),
        uniform_var("constants", Type::Custom("Constants".to_string()), 0, 1),
        Item::Comment("Group 1: Solution".to_string()),
        storage_var("x", Type::array(Type::F32), 1, 0, AccessMode::ReadWrite),
    ]
}

fn base_apply_items(eos_params: &[ParamSpec]) -> Vec<Item> {
    vec![
        Item::Struct(constants_struct(eos_params)),
        Item::Comment("Group 0: CSR matrix".to_string()),
        storage_var(
            "row_offsets",
            Type::array(Type::U32),
            0,
            0,
            AccessMode::Read,
        ),
        storage_var(
            "col_indices",
            Type::array(Type::U32),
            0,
            1,
            AccessMode::Read,
        ),
        storage_var(
            "matrix_values",
            Type::array(Type::F32),
            0,
            2,
            AccessMode::Read,
        ),
        Item::Comment("Group 1: vectors".to_string()),
        storage_var("x", Type::array(Type::F32), 1, 0, AccessMode::Read),
        storage_var("y", Type::array(Type::F32), 1, 1, AccessMode::ReadWrite),
        uniform_var("constants", Type::Custom("Constants".to_string()), 1, 2),
    ]
}

fn main_assembly_fn<Ax: typed::CoupledAxis>(
    system: &DiscreteSystem,
    slots: &ResolvedStateSlotsSpec,
) -> Function {
    // This legacy generator does not implement the transpose_dev2 viscous
    // block (the production unified_assembly generator does). Fail loudly
    // rather than silently dropping a declared term.
    assert!(
        !system
            .equations
            .iter()
            .any(|eq| eq.ops.iter().any(|op| op.transpose_dev2)),
        "generic_coupled_kernels::main_assembly_fn does not support transpose_dev2 terms; \
         use the unified_assembly generator"
    );
    let _stride = slots.stride;
    let unknowns = coupled_unknown_components(system);
    let coupled_stride = unknowns.len() as u32;
    let offsets = coupled_offsets(system);

    assert_eq!(
        Ax::STRIDE,
        coupled_stride,
        "main_assembly_fn: axis stride ({}) != coupled_stride ({coupled_stride})",
        Ax::STRIDE,
    );

    let acc = typed::CoupledAccumulators::new(coupled_stride);

    let params = vec![Param::new(
        "global_id",
        Type::vec3_u32(),
        vec![Attribute::Builtin("global_invocation_id".to_string())],
    )];

    let block_matrix = typed::NamedBlockCsrSoaMatrix::<Ax>::from_start_row_prefix(
        "matrix_values",
        "start_row",
        typed::ScalarType::F32,
        typed::UnitDim::dimensionless(),
    );

    let mut stmts = vec![
        dsl::let_expr(
            "idx",
            Expr::ident("global_id").field("y") * Expr::ident("constants").field("stride_x")
                + Expr::ident("global_id").field("x"),
        ),
        dsl::if_block_expr(
            Expr::ident("idx").ge(Expr::call_named(
                "arrayLength",
                vec![Expr::ident("cell_vols").addr_of()],
            )),
            dsl::block(vec![Stmt::Return(None)]),
            None,
        ),
        dsl::let_expr(
            "center",
            dsl::array_access("cell_centers", Expr::ident("idx")),
        ),
        dsl::let_expr("vol", dsl::array_access("cell_vols", Expr::ident("idx"))),
        dsl::let_expr(
            "start",
            dsl::array_access("cell_face_offsets", Expr::ident("idx")),
        ),
        dsl::let_expr(
            "end",
            dsl::array_access("cell_face_offsets", Expr::ident("idx") + 1u32),
        ),
        dsl::let_expr(
            "scalar_offset",
            dsl::array_access("scalar_row_offsets", Expr::ident("idx")),
        ),
        dsl::let_expr(
            "num_neighbors",
            dsl::array_access("scalar_row_offsets", Expr::ident("idx") + 1u32)
                - Expr::ident("scalar_offset"),
        ),
    ];
    // start_row_i = scalar_offset * block_stride + num_neighbors * coupled_stride * i
    stmts
        .extend(acc.declare_start_rows(Expr::ident("scalar_offset"), Expr::ident("num_neighbors")));

    // Clear all block entries for this cell's rows.
    stmts.push(dsl::for_loop_expr(
        dsl::for_init_var_expr("rank", 0u32),
        Expr::ident("rank").lt(Expr::ident("num_neighbors")),
        dsl::for_step_increment_expr(Expr::ident("rank")),
        dsl::block(dsl::for_each_mat_entry_block(
            coupled_stride as usize,
            |r, c| {
                vec![dsl::assign_expr(
                    block_matrix
                        .entry(
                            &Expr::ident("rank"),
                            typed::block_row::<Ax>(r as u32),
                            typed::block_col::<Ax>(c as u32),
                        )
                        .expr,
                    0.0,
                )]
            },
        )),
    ));

    // diag_i / rhs_i accumulators
    stmts.extend(acc.declare());

    // Time derivative contributions (implicit only).
    stmts.extend(super::coupled_common::emit_ddt_contributions(
           system, slots, &offsets, &acc,
    ));

    // Face loop for diffusion contributions (implicit only).
    let face_loop_body = {
        let mut body = vec![dsl::let_expr(
            "face_idx",
            dsl::array_access("cell_faces", Expr::ident("k")),
        )];
        body.push(dsl::let_expr(
            "owner",
            dsl::array_access("face_owner", Expr::ident("face_idx")),
        ));
        body.push(dsl::let_expr(
            "neighbor_raw",
            dsl::array_access("face_neighbor", Expr::ident("face_idx")),
        ));
        body.push(dsl::let_expr(
            "boundary_type",
            dsl::array_access("face_boundary", Expr::ident("face_idx")),
        ));
        body.push(dsl::let_expr(
            "area",
            dsl::array_access("face_areas", Expr::ident("face_idx")),
        ));
        body.push(dsl::let_expr(
            "f_center",
            dsl::array_access("face_centers", Expr::ident("face_idx")),
        ));
        body.push(dsl::var_typed_expr(
            "normal",
            Type::Custom("Vector2".to_string()),
            Some(dsl::array_access("face_normals", Expr::ident("face_idx"))),
        ));
        body.push(dsl::var_typed_expr(
            "is_boundary",
            Type::Bool,
            Some(false.into()),
        ));
        body.push(dsl::var_typed_expr(
            "other_idx",
            Type::U32,
            Some(Expr::ident("idx")),
        ));
        body.push(dsl::var_typed_expr(
            "other_center",
            Type::Custom("Vector2".to_string()),
            None,
        ));

        // Make normal outward from `idx`.
        body.push(dsl::if_block_expr(
            Expr::ident("owner").ne(Expr::ident("idx")),
            dsl::block(vec![
                dsl::assign_expr(
                    Expr::ident("normal").field("x"),
                    -Expr::ident("normal").field("x"),
                ),
                dsl::assign_expr(
                    Expr::ident("normal").field("y"),
                    -Expr::ident("normal").field("y"),
                ),
            ]),
            None,
        ));

        let interior_block = dsl::block(vec![
            dsl::let_expr(
                "neighbor",
                Expr::call_named("u32", vec![Expr::ident("neighbor_raw")]),
            ),
            dsl::assign_expr(Expr::ident("other_idx"), Expr::ident("neighbor")),
            dsl::if_block_expr(
                Expr::ident("owner").ne(Expr::ident("idx")),
                dsl::block(vec![dsl::assign_expr(
                    Expr::ident("other_idx"),
                    Expr::ident("owner"),
                )]),
                None,
            ),
            dsl::assign_expr(
                Expr::ident("other_center"),
                dsl::array_access("cell_centers", Expr::ident("other_idx")),
            ),
        ]);

        let boundary_block = dsl::block(vec![
            dsl::assign_expr(Expr::ident("is_boundary"), true),
            dsl::assign_expr(Expr::ident("other_idx"), Expr::ident("idx")),
            dsl::assign_expr(Expr::ident("other_center"), Expr::ident("f_center")),
        ]);

        body.push(dsl::if_block_expr(
            Expr::ident("neighbor_raw").ne(-1),
            interior_block,
            Some(boundary_block),
        ));

        body.push(dsl::let_expr(
            "dx",
            Expr::ident("other_center").field("x") - Expr::ident("center").field("x"),
        ));
        body.push(dsl::let_expr(
            "dy",
            Expr::ident("other_center").field("y") - Expr::ident("center").field("y"),
        ));
        body.push(dsl::let_expr(
            "dist_proj",
            dsl::abs(
                Expr::ident("dx") * Expr::ident("normal").field("x")
                    + Expr::ident("dy") * Expr::ident("normal").field("y"),
            ),
        ));
        body.push(dsl::let_expr(
            "dist_euc",
            dsl::sqrt(
                Expr::ident("dx") * Expr::ident("dx") + Expr::ident("dy") * Expr::ident("dy"),
            ),
        ));
        body.push(dsl::var_typed_expr(
            "dist",
            Type::F32,
            Some(dsl::max("dist_euc", 1e-6)),
        ));
        body.push(dsl::if_block_expr(
            Expr::ident("dist_proj").gt(1e-6),
            dsl::block(vec![dsl::assign_expr(
                Expr::ident("dist"),
                Expr::ident("dist_proj"),
            )]),
            None,
        ));

        body.push(dsl::let_expr(
            "scalar_mat_idx",
            dsl::array_access("cell_face_matrix_indices", Expr::ident("k")),
        ));
        body.push(dsl::let_expr(
            "neighbor_rank",
            Expr::ident("scalar_mat_idx") - Expr::ident("scalar_offset"),
        ));

        // Diffusion contributions per equation.
        for equation in &system.equations {
            let Some(diff_op) = equation.ops.iter().find(|op| {
                op.kind == DiscreteOpKind::Diffusion
                    && op.discretization == Discretization::Implicit
            }) else {
                continue;
            };

            let base_offset = *offsets
                .get(equation.target.name())
                .expect("missing target offset");

            let kappa = coefficient_value_expr(slots, diff_op.coeff.as_ref(), "idx", 1.0.into());

            let diff_coeff_name = format!("diff_coeff_{}", equation.target.name());
            body.push(dsl::let_expr(
                &diff_coeff_name,
                kappa.clone() * Expr::ident("area") / Expr::ident("dist"),
            ));

            for component in 0..equation.target.kind().component_count() as u32 {
                let u_idx = base_offset + component;
                let bc = BcTable::new(Expr::ident("face_idx"), coupled_stride);
                let (bc_kind_expr, bc_value_expr) = bc.lookup(u_idx);

                let interior_contrib = dsl::block(vec![
                    acc.add_diag(u_idx, Expr::ident(&diff_coeff_name)),
                    dsl::assign_op_expr(
                        AssignOp::Sub,
                        block_matrix
                            .entry(
                                &Expr::ident("neighbor_rank"),
                                typed::block_row::<Ax>(u_idx),
                                typed::block_col::<Ax>(u_idx),
                            )
                            .expr,
                        Expr::ident(&diff_coeff_name),
                    ),
                ]);

                let neumann_rhs = -(kappa.clone() * Expr::ident("area") * bc_value_expr.clone());
                let boundary_contrib = dsl::block(vec![dsl::if_block_expr(
                    bc_kind_expr.eq(GpuBcKind::Dirichlet),
                    dsl::block(vec![
                        acc.add_diag(u_idx, Expr::ident(&diff_coeff_name)),
                        acc.add_rhs(u_idx, Expr::ident(&diff_coeff_name) * bc_value_expr),
                    ]),
                    Some(dsl::block(vec![dsl::if_block_expr(
                        bc_kind_expr.eq(GpuBcKind::Neumann),
                        dsl::block(vec![acc.add_rhs(u_idx, neumann_rhs)]),
                        None,
                    )])),
                )]);

                body.push(dsl::if_block_expr(
                    !Expr::ident("is_boundary"),
                    interior_contrib,
                    Some(boundary_contrib),
                ));
            }
        }

        body
    };

    stmts.push(dsl::for_loop_expr(
        dsl::for_init_var_expr("k", Expr::ident("start")),
        Expr::ident("k").lt(Expr::ident("end")),
        dsl::for_step_increment_expr(Expr::ident("k")),
        dsl::block(face_loop_body),
    ));

    // Write diagonal block and RHS.
    stmts.push(dsl::let_expr(
        "diag_rank",
        dsl::array_access("diagonal_indices", Expr::ident("idx")) - Expr::ident("scalar_offset"),
    ));
    let diag_entry = block_matrix.row_entry(&Expr::ident("diag_rank"));
    stmts.extend(acc.writeback(
        |i| {
            diag_entry
                .entry(typed::block_row::<Ax>(i), typed::block_col::<Ax>(i))
                .expr
        },
        "rhs",
        Expr::ident("idx"),
    ));

    Function::new(
        "main",
        params,
        None,
        vec![
            Attribute::Compute,
            Attribute::WorkgroupSize(GENERIC_COUPLED_WORKGROUP_SIZE),
        ],
        Block::new(stmts),
    )
}

fn main_update_fn(
    system: &DiscreteSystem,
    slots: &ResolvedStateSlotsSpec,
    primitives: &[(u32, Expr)],
    apply_relaxation: bool,
    relaxation_requires_dtau: bool,
) -> Function {
    let stride = slots.stride;
    let unknowns = coupled_unknown_components(system);
    let coupled_stride = unknowns.len() as u32;

    let params = vec![Param::new(
        "global_id",
        Type::vec3_u32(),
        vec![Attribute::Builtin("global_invocation_id".to_string())],
    )];

    let mut stmts = Vec::new();
    stmts.push(dsl::let_expr(
        "idx",
        Expr::ident("global_id").field("y") * Expr::ident("constants").field("stride_x")
            + Expr::ident("global_id").field("x"),
    ));
    stmts.push(dsl::let_expr(
        "num_cells",
        Expr::call_named("arrayLength", vec![Expr::ident("state").addr_of()]) / stride,
    ));
    stmts.push(dsl::if_block_expr(
        Expr::ident("idx").ge(Expr::ident("num_cells")),
        dsl::block(vec![Stmt::Return(None)]),
        None,
    ));

    for (u_idx, (field, component)) in unknowns.iter().enumerate() {
        let field_slot = slots
            .slots
            .iter()
            .find(|s| s.name == field.name())
            .unwrap_or_else(|| panic!("missing field '{}' in resolved state slots", field.name()));
        let target = state_component_slot(slots.stride, "state", "idx", field_slot, *component);
        let x_entry =
            dsl::array_access_linear("x", Expr::ident("idx"), coupled_stride, u_idx as u32);
        let value = x_entry.clone();

        // Under-relaxation for SIMPLE-like coupled solvers.
        //
        // Only apply when enabled by the caller (e.g. incompressible pressure–velocity coupling).
        let alpha = if apply_relaxation {
            // Under-relax all non-pressure unknowns with alpha_u; treat pressure as a separate knob.
            let base_alpha = match field.name() {
                "p" => Expr::ident("constants").field("alpha_p"),
                _ => Expr::ident("constants").field("alpha_u"),
            };

            if relaxation_requires_dtau {
                // Preserve dtau=0 implicit stepping semantics: only apply relaxation in
                // pseudo-time (dual-time) iterations.
                dsl::select(
                    Expr::lit_f32(1.0),
                    base_alpha,
                    Expr::ident("constants")
                        .field("dtau")
                        .gt(Expr::lit_f32(0.0)),
                )
            } else {
                base_alpha
            }
        } else {
            Expr::lit_f32(1.0)
        };
        let prev = target.clone();
        let prev_is_finite = prev.clone().eq(prev.clone()) & dsl::abs(prev.clone()).lt(Expr::lit_f32(3.4e38));
        let value_is_finite = value.clone().eq(value.clone()) & dsl::abs(value.clone()).lt(Expr::lit_f32(3.4e38));

        // Avoid propagating NaN/Inf from the linear solver into the state.
        // If the previous iterate is already non-finite, prefer a finite `value`.
        let relaxed = Expr::call_named("mix", vec![prev.clone(), value.clone(), alpha]);
        let candidate = dsl::select(value.clone(), relaxed, prev_is_finite);
        let out = dsl::select(prev, candidate, value_is_finite);

        stmts.push(dsl::assign_expr(target, out.clone()));
        stmts.push(dsl::assign_expr(x_entry, out));
    }

    // Optional primitive recovery (derived primitives from conserved state).
    //
    // This is intentionally emitted inside the model-side update kernel to avoid
    // additional per-model registry plumbing.
    //
    // Primitives are pre-resolved to state offsets by the caller (model-side).
    if !primitives.is_empty() {
        let cell_idx = Expr::ident("idx");
        for (offset, expr) in primitives {
            let value = resolve_field_refs(expr, slots, cell_idx.clone(), "state");
            let target = dsl::array_access_linear("state", Expr::ident("idx"), stride, *offset);
            stmts.push(dsl::assign_expr(target, value));
        }
    }

    Function::new(
        "main",
        params,
        None,
        vec![
            Attribute::Compute,
            Attribute::WorkgroupSize(GENERIC_COUPLED_WORKGROUP_SIZE),
        ],
        Block::new(stmts),
    )
}

fn main_apply_fn() -> Function {
    main_apply_fn_with_index_var("row")
}

fn main_apply_fn_with_index_var(index_var: &str) -> Function {
    let params = vec![Param::new(
        "global_id",
        Type::vec3_u32(),
        vec![Attribute::Builtin("global_invocation_id".to_string())],
    )];

    let mut stmts = vec![
        dsl::let_expr(
            index_var,
            Expr::ident("global_id").field("y") * Expr::ident("constants").field("stride_x")
                + Expr::ident("global_id").field("x"),
        ),
        dsl::let_expr(
            "n",
            Expr::call_named("arrayLength", vec![Expr::ident("row_offsets").addr_of()]) - 1u32,
        ),
        dsl::if_block_expr(
            Expr::ident(index_var).ge(Expr::ident("n")),
            dsl::block(vec![Stmt::Return(None)]),
            None,
        ),
        dsl::let_expr(
            "start",
            dsl::array_access("row_offsets", Expr::ident(index_var)),
        ),
        dsl::let_expr(
            "end",
            dsl::array_access("row_offsets", Expr::ident(index_var) + 1u32),
        ),
        dsl::var_typed_expr("sum", Type::F32, Some(0.0.into())),
        dsl::for_loop_expr(
            dsl::for_init_var_expr("i", Expr::ident("start")),
            Expr::ident("i").lt(Expr::ident("end")),
            dsl::for_step_increment_expr(Expr::ident("i")),
            dsl::block(vec![
                dsl::let_expr("col", dsl::array_access("col_indices", Expr::ident("i"))),
                dsl::let_expr("val", dsl::array_access("matrix_values", Expr::ident("i"))),
                dsl::let_expr("x_val", dsl::array_access("x", Expr::ident("col"))),
                dsl::assign_op_expr(
                    AssignOp::Add,
                    Expr::ident("sum"),
                    Expr::ident("val") * Expr::ident("x_val"),
                ),
            ]),
        ),
    ];
    stmts.push(dsl::assign_expr(
        dsl::array_access("y", Expr::ident(index_var)),
        Expr::ident("sum"),
    ));

    Function::new(
        "main",
        params,
        None,
        vec![
            Attribute::Compute,
            Attribute::WorkgroupSize(GENERIC_COUPLED_WORKGROUP_SIZE),
        ],
        Block::new(stmts),
    )
}
#[cfg(test)]
mod tests {
    use super::*;
    use crate::solver::codegen::ir::lower_system;
    use crate::solver::ir::ports::{PortFieldKind, ResolvedStateSlotSpec, ResolvedStateSlotsSpec};
    use crate::solver::ir::{fvm, vol_scalar_dim, Equation, EquationSystem, SchemeRegistry};
    use crate::solver::scheme::Scheme;

    /// Helper to create a ResolvedStateSlotsSpec from a StateLayout for testing.
    fn slots_from_layout(layout: &crate::solver::ir::StateLayout) -> ResolvedStateSlotsSpec {
        let mut slots = vec![];
        for field in layout.fields() {
            let kind = match field.kind() {
                crate::solver::ir::FieldKind::Scalar => PortFieldKind::Scalar,
                crate::solver::ir::FieldKind::Vector2 => PortFieldKind::Vector2,
                crate::solver::ir::FieldKind::Vector3 => PortFieldKind::Vector3,
            };
            slots.push(ResolvedStateSlotSpec {
                name: field.name().to_string(),
                kind,
                unit: field.unit(),
                base_offset: field.offset(),
            });
        }
        ResolvedStateSlotsSpec {
            stride: layout.stride(),
            slots,
        }
    }

    /// Build a momentum-like system (coupled stride 3, like the real
    /// incompressible model): U eqn = ddt(rho, U) + dev2 term (both
    /// integrate to Force), plus a trivial p equation.
    fn dev2_system(
        u: crate::solver::ir::FieldRef,
        p: crate::solver::ir::FieldRef,
    ) -> EquationSystem {
        use crate::solver::ir::{fvc, Coefficient};
        let mut eqn = Equation::new(u);
        eqn.add_term(fvm::ddt_coeff(
            Coefficient::constant_unit(1.0, cfd2_ir::units::si::DENSITY),
            u,
        ));
        eqn.add_term(fvc::div_dev2_grad_transpose(
            Coefficient::constant_unit(0.01, cfd2_ir::units::si::DYNAMIC_VISCOSITY),
            u,
        ));
        let mut p_eqn = Equation::new(p);
        p_eqn.add_term(fvm::ddt(p));
        let mut system = EquationSystem::new();
        system.add_equation(eqn);
        system.add_equation(p_eqn);
        system
    }

    #[test]
    fn dev2_term_emits_grad_state_face_flux() {
        let u = crate::solver::ir::vol_vector_dim::<cfd2_ir::dimensions::Velocity>("U");
        let p = vol_scalar_dim::<cfd2_ir::dimensions::Pressure>("p");
        let system = dev2_system(u, p);

        let layout = crate::solver::ir::StateLayout::new(vec![u, p]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let wgsl = crate::solver::codegen::unified_assembly::generate_unified_assembly_wgsl(
            &discrete, &slots, 0, true, &[],
        )
        .to_wgsl();
        // Face gradients of both U components from grad_state (stride 3:
        // U_x=0, U_y=1, p=2), averaged owner/neighbor.
        assert!(
            wgsl.contains("grad_state[idx * 3u + 0u]")
                && wgsl.contains("grad_state[other_idx * 3u + 0u]"),
            "dev2 term must read the U_x gradient from grad_state:\n{wgsl}"
        );
        assert!(
            wgsl.contains("grad_state[idx * 3u + 1u]"),
            "dev2 term must read the U_y gradient from grad_state"
        );
        // Both component RHS accumulations with the face area.
        assert!(
            wgsl.contains("rhs_0 += dev2_U_U_mu * area")
                && wgsl.contains("rhs_1 += dev2_U_U_mu * area"),
            "dev2 term must accumulate mu * area * flux into both rhs components:\n{wgsl}"
        );
    }

    #[test]
    fn dev2_term_keys_grad_state_by_state_offset_not_rank() {
        // Non-prefix layout (buoyant-T-style): an aux scalar sits BEFORE the
        // unknown, so U's state offset (1) differs from its coupled rank (0).
        // grad_state is STATE-OFFSET keyed, not rank-keyed.
        let aux = vol_scalar_dim::<cfd2_ir::dimensions::Pressure>("aux");
        let u = crate::solver::ir::vol_vector_dim::<cfd2_ir::dimensions::Velocity>("U");
        let p = vol_scalar_dim::<cfd2_ir::dimensions::Pressure>("p");
        let system = dev2_system(u, p);

        // aux(0), U(1..2), p(3): U's state offsets differ from its ranks.
        let layout = crate::solver::ir::StateLayout::new(vec![aux, u, p]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let wgsl = crate::solver::codegen::unified_assembly::generate_unified_assembly_wgsl(
            &discrete, &slots, 0, true, &[],
        )
        .to_wgsl();
        assert!(
            wgsl.contains("grad_state[idx * 4u + 1u]")
                && wgsl.contains("grad_state[idx * 4u + 2u]"),
            "dev2 gradients must use U's STATE offsets 1/2, not coupled ranks:\n{wgsl}"
        );
        assert!(
            !wgsl.contains("grad_state[idx * 4u + 0u]"),
            "dev2 gradients must not read the aux slot (rank-keyed bug):\n{wgsl}"
        );
    }

    #[test]
    fn dev2_term_compiles_without_gradients_buffer() {
        // The non-grad assembly variant is still generated for every model;
        // it must compile with the two-point fallback (never scheduled once
        // the dev2 term forces the gradients pipeline on).
        let u = crate::solver::ir::vol_vector_dim::<cfd2_ir::dimensions::Velocity>("U");
        let p = vol_scalar_dim::<cfd2_ir::dimensions::Pressure>("p");
        let system = dev2_system(u, p);

        let layout = crate::solver::ir::StateLayout::new(vec![u, p]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let wgsl = crate::solver::codegen::unified_assembly::generate_unified_assembly_wgsl(
            &discrete, &slots, 0, false, &[],
        )
        .to_wgsl();
        assert!(
            !wgsl.contains("grad_state"),
            "non-grad variant must not reference grad_state"
        );
        assert!(
            wgsl.contains("rhs_0 += dev2_U_U_mu * area"),
            "non-grad variant still emits the dev2 accumulation via the fallback gradient"
        );
    }

    #[test]
    fn generic_coupled_ddt_adds_dtau_diagonal_when_enabled() {
        let u = vol_scalar_dim::<cfd2_ir::dimensions::Velocity>("u");

        let mut eqn = Equation::new(u);
        eqn.add_term(fvm::ddt(u));

        let mut system = EquationSystem::new();
        system.add_equation(eqn);

        let layout = crate::solver::ir::StateLayout::new(vec![u]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let wgsl = generate_generic_coupled_assembly_wgsl(&discrete, &slots, false, &[]).to_wgsl();
        assert!(
            wgsl.contains("constants.dtau > 0.0"),
            "expected assembly WGSL to gate dual-time term on constants.dtau"
        );
        assert!(
            wgsl.contains("perimeter_sum") && wgsl.contains("face_metric_scale"),
            "expected assembly WGSL to include the face-based local dtau metric"
        );
    }

        #[test]
    fn generic_coupled_ddt_face_metric_uses_square_cell_normalization() {
        let u = vol_scalar_dim::<cfd2_ir::dimensions::Velocity>("u");

        let mut eqn = Equation::new(u);
        eqn.add_term(fvm::ddt(u));

            let mut system = EquationSystem::new();
            system.add_equation(eqn);

        let layout = crate::solver::ir::StateLayout::new(vec![u]);
            let slots = slots_from_layout(&layout);
            let schemes = SchemeRegistry::new(Scheme::Upwind);
            let discrete = lower_system(&system, &schemes).expect("lower_system");
        let wgsl = generate_generic_coupled_assembly_wgsl(&discrete, &slots, false, &[]).to_wgsl();

            assert!(
            wgsl.contains("perimeter_sum * perimeter_sum"),
            "expected assembly WGSL to build the face-based perimeter metric"
            );
            assert!(
            wgsl.contains("16.0 * vol") || wgsl.contains("16f * vol"),
            "expected assembly WGSL to normalize the face metric against a square-cell reference"
            );
        }

    #[test]
    fn generic_coupled_update_program_extracts_launch_and_body_from_dsl() {
        let u = vol_scalar_dim::<cfd2_ir::dimensions::Velocity>("u");

        let mut eqn = Equation::new(u);
        eqn.add_term(fvm::ddt(u));

        let mut system = EquationSystem::new();
        system.add_equation(eqn);

        let layout = crate::solver::ir::StateLayout::new(vec![u]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let program = generate_generic_coupled_update_kernel_program(
            "generic_coupled_update",
            &discrete,
            &slots,
            &[],
            false,
            false,
            &[],
        )
        .expect("generate update kernel program");

        assert_eq!(program.id, "generic_coupled_update");
        assert_eq!(
            program.launch.invocation_index_expr,
            "global_id.y * constants.stride_x + global_id.x"
        );
        assert_eq!(
            program.launch.bounds_check_expr.as_deref(),
            Some("idx >= (arrayLength(&state) / 1u)")
        );
        let rendered = cfd2_ir::ast::stmt::render_stmt_lines(&program.body);
        assert!(
            !rendered.iter().any(|line| line.contains("let idx")),
            "idx declaration should be represented by launch semantics, not body lines"
        );
        assert!(
            !rendered.iter().any(|line| line.contains("num_cells")),
            "num_cells helper should be folded into launch bounds check"
        );
    }

    #[test]
    fn generic_coupled_update_program_local_symbols_exclude_launch_aliases() {
        let u = vol_scalar_dim::<cfd2_ir::dimensions::Velocity>("u");

        let mut eqn = Equation::new(u);
        eqn.add_term(fvm::ddt(u));

        let mut system = EquationSystem::new();
        system.add_equation(eqn);

        let layout = crate::solver::ir::StateLayout::new(vec![u]);
        let slots = slots_from_layout(&layout);
        let schemes = SchemeRegistry::new(Scheme::Upwind);
        let discrete = lower_system(&system, &schemes).expect("lower_system");

        let program = generate_generic_coupled_update_kernel_program(
            "generic_coupled_update",
            &discrete,
            &slots,
            &[],
            true,
            false,
            &[],
        )
        .expect("generate update kernel program");

        assert!(
            program.local_symbols().is_empty(),
            "update body emits no `let`/`var` declarations after launch extraction"
        );
        assert!(
            !program.local_symbols().iter().any(|s| s == "idx"),
            "`idx` launch alias should not be tracked as a renameable local symbol"
        );
        assert!(
            !program.local_symbols().iter().any(|s| s == "num_cells"),
            "`num_cells` launch helper should not remain after launch extraction"
        );
    }
}
