pub mod async_buffer;
pub mod bindings;
pub mod buffers;
pub mod context;
pub mod csr;
pub mod enums;
pub mod execution_plan;
pub mod init;
pub mod linear_solver;
pub(crate) mod lowering;
pub mod modules;
pub(crate) mod plans;
pub mod profiling;
pub mod readback;
pub mod recipe;
pub(crate) mod runtime;
pub(crate) mod runtime_common;
pub mod structs;
pub mod unified_solver;
pub(crate) mod wgsl_reflect;

pub use recipe::{LinearSolverSpec, SolverRecipe, TimeIntegrationSpec};
pub use unified_solver::{FgmresSizing, GpuUnifiedSolver, SolverConfig};
