use super::super::state_access::state_component;
use super::super::wgsl_ast::{
    AccessMode, Attribute, Block, Expr, Function, GlobalVar, Item, Module, Param, Stmt, StructDef,
    StructField, Type,
};
use super::super::wgsl_dsl as dsl;
use crate::solver::model::backend::{EquationSystem, FieldKind};
use crate::solver::model::backend::StateLayout;

pub fn generate_ei_apply_wgsl(layout: &StateLayout, system: &EquationSystem) -> String {
    let mut module = Module::new();
    module.push(Item::Comment(
        "GENERATED BY CFD2 CODEGEN (ei_apply)".to_string(),
    ));
    module.push(Item::Comment("DO NOT EDIT MANUALLY".to_string()));
    module.extend(base_items());
    module.push(Item::Function(main_fn(layout, system)));
    module.to_wgsl()
}

fn base_items() -> Vec<Item> {
    let mut items = Vec::new();
    items.push(Item::Struct(vector2_struct()));
    items.push(Item::Struct(constants_struct()));
    items.push(Item::Struct(low_mach_params_struct()));
    items.push(Item::Comment(
        "Group 0: Fields (consolidated state buffers)".to_string(),
    ));
    items.extend(state_bindings());
    items.push(Item::Comment("Group 1: Solver".to_string()));
    items.extend(solver_bindings());
    items
}

fn vector2_struct() -> StructDef {
    StructDef::new(
        "Vector2",
        vec![
            StructField::new("x", Type::F32),
            StructField::new("y", Type::F32),
        ],
    )
}

fn constants_struct() -> StructDef {
    StructDef::new(
        "Constants",
        vec![
            StructField::new("dt", Type::F32),
            StructField::new("dt_old", Type::F32),
            StructField::new("dtau", Type::F32),
            StructField::new("time", Type::F32),
            StructField::new("viscosity", Type::F32),
            StructField::new("density", Type::F32),
            StructField::new("component", Type::U32),
            StructField::new("alpha_p", Type::F32),
            StructField::new("scheme", Type::U32),
            StructField::new("alpha_u", Type::F32),
            StructField::new("stride_x", Type::U32),
            StructField::new("time_scheme", Type::U32),
            StructField::new("inlet_velocity", Type::F32),
            StructField::new("ramp_time", Type::F32),
        ],
    )
}

fn low_mach_params_struct() -> StructDef {
    StructDef::new(
        "LowMachParams",
        vec![
            StructField::new("model", Type::U32),
            StructField::new("theta_floor", Type::F32),
            StructField::new("pressure_coupling_alpha", Type::F32),
            StructField::new("_pad0", Type::F32),
        ],
    )
}

fn state_bindings() -> Vec<Item> {
    vec![
        storage_var("state", Type::array(Type::F32), 0, 0, AccessMode::ReadWrite),
        storage_var("state_old", Type::array(Type::F32), 0, 1, AccessMode::Read),
        storage_var(
            "state_old_old",
            Type::array(Type::F32),
            0,
            2,
            AccessMode::Read,
        ),
        storage_var(
            "fluxes",
            Type::array(Type::F32),
            0,
            3,
            AccessMode::ReadWrite,
        ),
        uniform_var("constants", Type::Custom("Constants".to_string()), 0, 4),
        storage_var(
            "grad_rho",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            5,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_u_x",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            6,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_u_y",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            7,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_e",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            8,
            AccessMode::ReadWrite,
        ),
        storage_var("state_iter", Type::array(Type::F32), 0, 9, AccessMode::Read),
        uniform_var("low_mach", Type::Custom("LowMachParams".to_string()), 0, 10),
    ]
}

fn solver_bindings() -> Vec<Item> {
    vec![storage_var(
        "solution",
        Type::array(Type::F32),
        1,
        0,
        AccessMode::Read,
    )]
}

fn storage_var(name: &str, ty: Type, group: u32, binding: u32, access: AccessMode) -> Item {
    Item::GlobalVar(GlobalVar::new(
        name,
        ty,
        super::super::wgsl_ast::StorageClass::Storage,
        Some(access),
        vec![Attribute::Group(group), Attribute::Binding(binding)],
    ))
}

fn uniform_var(name: &str, ty: Type, group: u32, binding: u32) -> Item {
    Item::GlobalVar(GlobalVar::new(
        name,
        ty,
        super::super::wgsl_ast::StorageClass::Uniform,
        None,
        vec![Attribute::Group(group), Attribute::Binding(binding)],
    ))
}

fn main_fn(layout: &StateLayout, system: &EquationSystem) -> Function {
    let params = vec![Param::new(
        "global_id",
        Type::vec3_u32(),
        vec![Attribute::Builtin("global_invocation_id".to_string())],
    )];
    Function::new(
        "main",
        params,
        None,
        vec![Attribute::Compute, Attribute::WorkgroupSize(64)],
        main_body(layout, system),
    )
}

fn main_body(layout: &StateLayout, system: &EquationSystem) -> Block {
    let mut stmts = Vec::new();
    let unknowns_per_cell = system.unknowns_per_cell();
    let mut unknown_components: Vec<(&str, u32)> = Vec::new();
    for eqn in system.equations() {
        let target = eqn.target();
        match target.kind() {
            FieldKind::Scalar => unknown_components.push((target.name(), 0)),
            FieldKind::Vector2 => {
                unknown_components.push((target.name(), 0));
                unknown_components.push((target.name(), 1));
            }
        }
    }

    stmts.push(dsl::let_expr("idx", Expr::ident("global_id").field("x")));
    stmts.push(dsl::let_expr(
        "num_cells",
        Expr::call_named("arrayLength", vec![Expr::ident("state").addr_of()]),
    ));
    stmts.push(dsl::if_block_expr(
        (Expr::ident("idx") * layout.stride()).ge("num_cells"),
        dsl::block(vec![Stmt::Return(None)]),
        None,
    ));

    stmts.push(dsl::let_expr(
        "relax",
        Expr::ident("constants").field("alpha_u"),
    ));

    stmts.push(dsl::let_expr(
        "base",
        Expr::ident("idx") * Expr::from(unknowns_per_cell),
    ));

    for (offset, (field, component)) in unknown_components.iter().enumerate() {
        let target = state_component(layout, "state", "idx", field, *component);
        let delta = Expr::ident("solution")
            .index(Expr::ident("base") + Expr::from(offset as u32));
        stmts.push(dsl::assign_expr(
            target.clone(),
            target + Expr::ident("relax") * delta,
        ));
    }

    Block::new(stmts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::solver::model::compressible_model;

    #[test]
    fn compressible_apply_codegen_emits_solution_binding() {
        let model = compressible_model();
        let wgsl = generate_ei_apply_wgsl(&model.state_layout, &model.system);
        assert!(wgsl.contains("solution"));
        assert!(wgsl.contains("alpha_u"));
        assert!(wgsl.contains("state_old"));
    }
}
