use crate::solver::model::CompressibleFields;
use crate::solver::model::backend::StateLayout;
use super::state_access::{state_scalar_expr, state_vec2_expr};
use super::reconstruction::scalar_reconstruction;
use super::wgsl_ast::{
    AccessMode, AssignOp, Attribute, Block, Function, GlobalVar, Item, Module, Param, Stmt,
    StructDef, StructField, Type,
};
use super::wgsl_dsl as dsl;

pub fn generate_compressible_assembly_wgsl(
    layout: &StateLayout,
    fields: &CompressibleFields,
) -> String {
    let mut module = Module::new();
    module.push(Item::Comment(
        "GENERATED BY CFD2 CODEGEN (compressible_assembly)".to_string(),
    ));
    module.push(Item::Comment("DO NOT EDIT MANUALLY".to_string()));
    module.extend(base_items());
    module.push(Item::Function(main_fn(layout, fields)));
    module.to_wgsl()
}

fn base_items() -> Vec<Item> {
    let mut items = Vec::new();
    items.push(Item::Struct(vector2_struct()));
    items.push(Item::Struct(constants_struct()));
    items.push(Item::Comment("Group 0: Mesh".to_string()));
    items.extend(mesh_bindings());
    items.push(Item::Comment(
        "Group 1: Fields (consolidated state buffers)".to_string(),
    ));
    items.extend(state_bindings());
    items.push(Item::Comment("Group 2: Solver".to_string()));
    items.extend(solver_bindings());
    items
}

fn vector2_struct() -> StructDef {
    StructDef::new(
        "Vector2",
        vec![
            StructField::new("x", Type::F32),
            StructField::new("y", Type::F32),
        ],
    )
}

fn constants_struct() -> StructDef {
    StructDef::new(
        "Constants",
        vec![
            StructField::new("dt", Type::F32),
            StructField::new("dt_old", Type::F32),
            StructField::new("time", Type::F32),
            StructField::new("viscosity", Type::F32),
            StructField::new("density", Type::F32),
            StructField::new("component", Type::U32),
            StructField::new("alpha_p", Type::F32),
            StructField::new("scheme", Type::U32),
            StructField::new("alpha_u", Type::F32),
            StructField::new("stride_x", Type::U32),
            StructField::new("time_scheme", Type::U32),
            StructField::new("inlet_velocity", Type::F32),
            StructField::new("ramp_time", Type::F32),
            StructField::new("precond_type", Type::U32),
        ],
    )
}

fn mesh_bindings() -> Vec<Item> {
    vec![
        storage_var(
            "face_owner",
            Type::array(Type::U32),
            0,
            0,
            AccessMode::Read,
        ),
        storage_var(
            "face_neighbor",
            Type::array(Type::I32),
            0,
            1,
            AccessMode::Read,
        ),
        storage_var(
            "face_areas",
            Type::array(Type::F32),
            0,
            2,
            AccessMode::Read,
        ),
        storage_var(
            "face_normals",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            3,
            AccessMode::Read,
        ),
        storage_var(
            "cell_centers",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            4,
            AccessMode::Read,
        ),
        storage_var(
            "cell_vols",
            Type::array(Type::F32),
            0,
            5,
            AccessMode::Read,
        ),
        storage_var(
            "cell_face_offsets",
            Type::array(Type::U32),
            0,
            6,
            AccessMode::Read,
        ),
        storage_var(
            "cell_faces",
            Type::array(Type::U32),
            0,
            7,
            AccessMode::Read,
        ),
        storage_var(
            "cell_face_matrix_indices",
            Type::array(Type::U32),
            0,
            8,
            AccessMode::Read,
        ),
        storage_var(
            "diagonal_indices",
            Type::array(Type::U32),
            0,
            9,
            AccessMode::Read,
        ),
        storage_var(
            "face_boundary",
            Type::array(Type::U32),
            0,
            12,
            AccessMode::Read,
        ),
        storage_var(
            "face_centers",
            Type::array(Type::Custom("Vector2".to_string())),
            0,
            13,
            AccessMode::Read,
        ),
    ]
}

fn state_bindings() -> Vec<Item> {
    vec![
        storage_var(
            "state",
            Type::array(Type::F32),
            1,
            0,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "state_old",
            Type::array(Type::F32),
            1,
            1,
            AccessMode::Read,
        ),
        storage_var(
            "state_old_old",
            Type::array(Type::F32),
            1,
            2,
            AccessMode::Read,
        ),
        storage_var(
            "fluxes",
            Type::array(Type::F32),
            1,
            3,
            AccessMode::ReadWrite,
        ),
        uniform_var("constants", Type::Custom("Constants".to_string()), 1, 4),
        storage_var(
            "grad_rho",
            Type::array(Type::Custom("Vector2".to_string())),
            1,
            5,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_u_x",
            Type::array(Type::Custom("Vector2".to_string())),
            1,
            6,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_u_y",
            Type::array(Type::Custom("Vector2".to_string())),
            1,
            7,
            AccessMode::ReadWrite,
        ),
        storage_var(
            "grad_rho_e",
            Type::array(Type::Custom("Vector2".to_string())),
            1,
            8,
            AccessMode::ReadWrite,
        ),
    ]
}

fn solver_bindings() -> Vec<Item> {
    vec![
        storage_var(
            "matrix_values",
            Type::array(Type::F32),
            2,
            0,
            AccessMode::ReadWrite,
        ),
        storage_var("rhs", Type::array(Type::F32), 2, 1, AccessMode::ReadWrite),
        storage_var(
            "scalar_row_offsets",
            Type::array(Type::U32),
            2,
            2,
            AccessMode::Read,
        ),
    ]
}

fn storage_var(
    name: &str,
    ty: Type,
    group: u32,
    binding: u32,
    access: AccessMode,
) -> Item {
    Item::GlobalVar(GlobalVar::new(
        name,
        ty,
        super::wgsl_ast::StorageClass::Storage,
        Some(access),
        vec![Attribute::Group(group), Attribute::Binding(binding)],
    ))
}

fn uniform_var(name: &str, ty: Type, group: u32, binding: u32) -> Item {
    Item::GlobalVar(GlobalVar::new(
        name,
        ty,
        super::wgsl_ast::StorageClass::Uniform,
        None,
        vec![Attribute::Group(group), Attribute::Binding(binding)],
    ))
}

fn main_fn(layout: &StateLayout, fields: &CompressibleFields) -> Function {
    let params = vec![Param::new(
        "global_id",
        Type::vec3_u32(),
        vec![Attribute::Builtin("global_invocation_id".to_string())],
    )];
    Function::new(
        "main",
        params,
        None,
        vec![Attribute::Compute, Attribute::WorkgroupSize(64)],
        main_body(layout, fields),
    )
}

fn main_body(layout: &StateLayout, fields: &CompressibleFields) -> Block {
    let mut stmts = Vec::new();
    let rho_field = fields.rho.name();
    let rho_u_field = fields.rho_u.name();
    let rho_e_field = fields.rho_e.name();
    let gamma = "1.4";
    let block_size = 4u32;
    let block_stride = block_size * block_size;

    stmts.push(dsl::let_("idx", "global_id.x"));
    stmts.push(dsl::if_block(
        "idx >= arrayLength(&cell_vols)",
        dsl::block(vec![Stmt::Return(None)]),
        None,
    ));
    stmts.push(dsl::let_("center", "cell_centers[idx]"));
    stmts.push(dsl::let_("start", "cell_face_offsets[idx]"));
    stmts.push(dsl::let_("end", "cell_face_offsets[idx + 1u]"));
    stmts.push(dsl::let_("vol", "cell_vols[idx]"));
    stmts.push(dsl::let_("scalar_offset", "scalar_row_offsets[idx]"));
    stmts.push(dsl::let_(
        "num_neighbors",
        "scalar_row_offsets[idx + 1u] - scalar_offset",
    ));
    stmts.push(dsl::let_(
        "start_row_0",
        &format!("{block_stride}u * scalar_offset"),
    ));
    stmts.push(dsl::let_(
        "start_row_1",
        &format!("start_row_0 + {}u * num_neighbors", block_size),
    ));
    stmts.push(dsl::let_(
        "start_row_2",
        &format!("start_row_0 + {}u * num_neighbors", block_size * 2),
    ));
    stmts.push(dsl::let_(
        "start_row_3",
        &format!("start_row_0 + {}u * num_neighbors", block_size * 3),
    ));
    stmts.push(dsl::let_("scheme_id", "constants.scheme"));

    stmts.push(dsl::comment("Jacobian rows/cols: rho, rho_u_x, rho_u_y, rho_e"));
    stmts.push(dsl::var("diag_00", "0.0"));
    stmts.push(dsl::var("diag_01", "0.0"));
    stmts.push(dsl::var("diag_02", "0.0"));
    stmts.push(dsl::var("diag_03", "0.0"));
    stmts.push(dsl::var("diag_10", "0.0"));
    stmts.push(dsl::var("diag_11", "0.0"));
    stmts.push(dsl::var("diag_12", "0.0"));
    stmts.push(dsl::var("diag_13", "0.0"));
    stmts.push(dsl::var("diag_20", "0.0"));
    stmts.push(dsl::var("diag_21", "0.0"));
    stmts.push(dsl::var("diag_22", "0.0"));
    stmts.push(dsl::var("diag_23", "0.0"));
    stmts.push(dsl::var("diag_30", "0.0"));
    stmts.push(dsl::var("diag_31", "0.0"));
    stmts.push(dsl::var("diag_32", "0.0"));
    stmts.push(dsl::var("diag_33", "0.0"));

    stmts.push(dsl::var("sum_rho", "0.0"));
    stmts.push(dsl::var("sum_rho_u_x", "0.0"));
    stmts.push(dsl::var("sum_rho_u_y", "0.0"));
    stmts.push(dsl::var("sum_rho_e", "0.0"));

    let rho_expr = state_scalar_expr(layout, "state", "idx", rho_field);
    let rho_u_expr = state_vec2_expr(layout, "state", "idx", rho_u_field);
    let rho_e_expr = state_scalar_expr(layout, "state", "idx", rho_e_field);
    let rho_old_expr = state_scalar_expr(layout, "state_old", "idx", rho_field);
    let rho_u_old_expr = state_vec2_expr(layout, "state_old", "idx", rho_u_field);
    let rho_e_old_expr = state_scalar_expr(layout, "state_old", "idx", rho_e_field);
    stmts.push(dsl::let_("rho", &rho_expr));
    stmts.push(dsl::let_("rho_u", &rho_u_expr));
    stmts.push(dsl::let_("rho_e", &rho_e_expr));
    stmts.push(dsl::let_("rho_old", &rho_old_expr));
    stmts.push(dsl::let_("rho_u_old", &rho_u_old_expr));
    stmts.push(dsl::let_("rho_e_old", &rho_e_old_expr));

    stmts.push(dsl::var("coeff_time", "vol / constants.dt"));
    stmts.push(dsl::var("rhs_time_rho", "coeff_time * rho_old"));
    stmts.push(dsl::var("rhs_time_rho_u_x", "coeff_time * rho_u_old.x"));
    stmts.push(dsl::var("rhs_time_rho_u_y", "coeff_time * rho_u_old.y"));
    stmts.push(dsl::var("rhs_time_rho_e", "coeff_time * rho_e_old"));

    let rho_old_old_expr = state_scalar_expr(layout, "state_old_old", "idx", rho_field);
    let rho_u_old_old_expr = state_vec2_expr(layout, "state_old_old", "idx", rho_u_field);
    let rho_e_old_old_expr = state_scalar_expr(layout, "state_old_old", "idx", rho_e_field);
    let bdf2_block = dsl::block(vec![
        dsl::let_("dt", "constants.dt"),
        dsl::let_("dt_old", "constants.dt_old"),
        dsl::let_("r", "dt / dt_old"),
        dsl::let_("rho_old_old", &rho_old_old_expr),
        dsl::let_("rho_u_old_old", &rho_u_old_old_expr),
        dsl::let_("rho_e_old_old", &rho_e_old_old_expr),
        dsl::assign(
            "coeff_time",
            "vol / dt * (1.0 + 2.0 * r) / (1.0 + r)",
        ),
        dsl::let_("factor_n", "(1.0 + r)"),
        dsl::let_("factor_nm1", "(r * r) / (1.0 + r)"),
        dsl::assign(
            "rhs_time_rho",
            "(vol / dt) * (factor_n * rho_old - factor_nm1 * rho_old_old)",
        ),
        dsl::assign(
            "rhs_time_rho_u_x",
            "(vol / dt) * (factor_n * rho_u_old.x - factor_nm1 * rho_u_old_old.x)",
        ),
        dsl::assign(
            "rhs_time_rho_u_y",
            "(vol / dt) * (factor_n * rho_u_old.y - factor_nm1 * rho_u_old_old.y)",
        ),
        dsl::assign(
            "rhs_time_rho_e",
            "(vol / dt) * (factor_n * rho_e_old - factor_nm1 * rho_e_old_old)",
        ),
    ]);

    stmts.push(dsl::if_block(
        "constants.time_scheme == 1u",
        bdf2_block,
        None,
    ));

    let rho_r_expr = state_scalar_expr(layout, "state", "other_idx", rho_field);
    let rho_u_r_expr = state_vec2_expr(layout, "state", "other_idx", rho_u_field);
    let rho_e_r_expr = state_scalar_expr(layout, "state", "other_idx", rho_e_field);

    let mut loop_body = Vec::new();
    loop_body.push(dsl::let_("face_idx", "cell_faces[face_offset]"));
    loop_body.push(dsl::let_("owner", "face_owner[face_idx]"));
    loop_body.push(dsl::let_("neighbor", "face_neighbor[face_idx]"));
    loop_body.push(dsl::let_("boundary_type", "face_boundary[face_idx]"));
    loop_body.push(dsl::let_("area", "face_areas[face_idx]"));
    loop_body.push(dsl::var("normal", "face_normals[face_idx]"));
    loop_body.push(dsl::let_("f_center", "face_centers[face_idx]"));
    loop_body.push(dsl::var("is_boundary", "false"));
    loop_body.push(dsl::var("other_idx", "0u"));
    loop_body.push(dsl::var_typed(
        "center_r",
        Type::Custom("Vector2".to_string()),
        None,
    ));

    loop_body.push(dsl::if_block(
        "owner != idx",
        dsl::block(vec![
            dsl::assign("normal.x", "-normal.x"),
            dsl::assign("normal.y", "-normal.y"),
        ]),
        None,
    ));

    let interior_block = dsl::block(vec![
        dsl::let_("neigh_idx", "u32(neighbor)"),
        dsl::assign("other_idx", "neigh_idx"),
        dsl::if_block(
            "owner != idx",
            dsl::block(vec![dsl::assign("other_idx", "owner")]),
            None,
        ),
        dsl::assign("center_r", "cell_centers[other_idx]"),
        dsl::let_("rho_neigh", &rho_r_expr),
        dsl::let_("rho_u_neigh", &rho_u_r_expr),
        dsl::let_("rho_e_neigh", &rho_e_r_expr),
        dsl::assign("rho_r", "rho_neigh"),
        dsl::assign("rho_u_r.x", "rho_u_neigh.x"),
        dsl::assign("rho_u_r.y", "rho_u_neigh.y"),
        dsl::assign("rho_e_r", "rho_e_neigh"),
    ]);

    let boundary_block = dsl::block(vec![
        dsl::assign("is_boundary", "true"),
        dsl::assign("other_idx", "idx"),
        dsl::assign("center_r", "f_center"),
    ]);

    let rho_l_expr = state_scalar_expr(layout, "state", "idx", rho_field);
    let rho_u_l_expr = state_vec2_expr(layout, "state", "idx", rho_u_field);
    let rho_e_l_expr = state_scalar_expr(layout, "state", "idx", rho_e_field);
    loop_body.push(dsl::let_("rho_l", &rho_l_expr));
    loop_body.push(dsl::let_("rho_u_l", &rho_u_l_expr));
    loop_body.push(dsl::let_("rho_e_l", &rho_e_l_expr));
    loop_body.push(dsl::var("rho_r", "rho_l"));
    loop_body.push(dsl::var("rho_u_r", "rho_u_l"));
    loop_body.push(dsl::var("rho_e_r", "rho_e_l"));

    loop_body.push(dsl::if_block(
        "neighbor != -1",
        interior_block,
        Some(boundary_block),
    ));

    let boundary_state = dsl::block(vec![dsl::if_block(
        "boundary_type == 1u",
        dsl::block(vec![
            dsl::assign("rho_u_r.x", "rho_r * constants.inlet_velocity"),
            dsl::assign("rho_u_r.y", "0.0"),
        ]),
        Some(dsl::block(vec![dsl::if_block(
            "boundary_type == 3u",
            dsl::block(vec![
                dsl::assign("rho_u_r.x", "-rho_u_l.x"),
                dsl::assign("rho_u_r.y", "-rho_u_l.y"),
            ]),
            None,
        )])),
    )]);

    loop_body.push(dsl::if_block("is_boundary", boundary_state, None));

    loop_body.push(dsl::let_("inv_rho_l", "1.0 / max(rho_l, 1e-8)"));
    loop_body.push(dsl::let_("u_l_x", "rho_u_l.x * inv_rho_l"));
    loop_body.push(dsl::let_("u_l_y", "rho_u_l.y * inv_rho_l"));
    loop_body.push(dsl::let_("ke_l", "0.5 * rho_l * (u_l_x * u_l_x + u_l_y * u_l_y)"));
    loop_body.push(dsl::let_(
        "p_l",
        &format!("max(0.0, ({gamma} - 1.0) * (rho_e_l - ke_l))"),
    ));
    loop_body.push(dsl::let_("u_n_l", "u_l_x * normal.x + u_l_y * normal.y"));
    loop_body.push(dsl::let_("c_l", &format!("sqrt({gamma} * p_l * inv_rho_l)")));

    loop_body.push(dsl::let_("inv_rho_r", "1.0 / max(rho_r, 1e-8)"));
    loop_body.push(dsl::let_("u_r_x", "rho_u_r.x * inv_rho_r"));
    loop_body.push(dsl::let_("u_r_y", "rho_u_r.y * inv_rho_r"));
    loop_body.push(dsl::let_("ke_r", "0.5 * rho_r * (u_r_x * u_r_x + u_r_y * u_r_y)"));
    loop_body.push(dsl::let_(
        "p_r",
        &format!("max(0.0, ({gamma} - 1.0) * (rho_e_r - ke_r))"),
    ));
    loop_body.push(dsl::let_("u_n_r", "u_r_x * normal.x + u_r_y * normal.y"));
    loop_body.push(dsl::let_("c_r", &format!("sqrt({gamma} * p_r * inv_rho_r)")));
    loop_body.push(dsl::let_("u_face_x", "0.5 * (u_l_x + u_r_x)"));
    loop_body.push(dsl::let_("u_face_y", "0.5 * (u_l_y + u_r_y)"));
    loop_body.push(dsl::let_("u_face_n", "u_face_x * normal.x + u_face_y * normal.y"));
    loop_body.push(dsl::let_("flux_adv", "u_face_n * area"));
    loop_body.push(dsl::let_("dx", "center_r.x - center.x"));
    loop_body.push(dsl::let_("dy", "center_r.y - center.y"));
    loop_body.push(dsl::let_("dist", "max(sqrt(dx * dx + dy * dy), 1e-6)"));
    loop_body.push(dsl::let_("mu", "constants.viscosity"));

    loop_body.push(dsl::let_(
        "a_plus",
        "max(0.0, max(u_n_l + c_l, u_n_r + c_r))",
    ));
    loop_body.push(dsl::let_(
        "a_minus",
        "min(0.0, min(u_n_l - c_l, u_n_r - c_r))",
    ));
    loop_body.push(dsl::let_("denom", "max(a_plus - a_minus, 1e-6)"));
    loop_body.push(dsl::let_("a_prod", "a_plus * a_minus"));

    loop_body.push(dsl::let_("f_rho_l", "rho_l * u_n_l"));
    loop_body.push(dsl::let_("f_rho_r", "rho_r * u_n_r"));
    loop_body.push(dsl::let_(
        "flux_rho",
        "(a_plus * f_rho_l - a_minus * f_rho_r + a_prod * (rho_r - rho_l)) / denom",
    ));

    loop_body.push(dsl::let_("f_rho_u_l_x", "rho_u_l.x * u_n_l + p_l * normal.x"));
    loop_body.push(dsl::let_("f_rho_u_l_y", "rho_u_l.y * u_n_l + p_l * normal.y"));
    loop_body.push(dsl::let_("f_rho_u_r_x", "rho_u_r.x * u_n_r + p_r * normal.x"));
    loop_body.push(dsl::let_("f_rho_u_r_y", "rho_u_r.y * u_n_r + p_r * normal.y"));
    loop_body.push(dsl::var(
        "flux_rho_u_x",
        "(a_plus * f_rho_u_l_x - a_minus * f_rho_u_r_x + a_prod * (rho_u_r.x - rho_u_l.x)) / denom",
    ));
    loop_body.push(dsl::var(
        "flux_rho_u_y",
        "(a_plus * f_rho_u_l_y - a_minus * f_rho_u_r_y + a_prod * (rho_u_r.y - rho_u_l.y)) / denom",
    ));
    loop_body.push(dsl::let_(
        "diff_u_x",
        "-mu * (u_r_x - u_l_x) / dist",
    ));
    loop_body.push(dsl::let_(
        "diff_u_y",
        "-mu * (u_r_y - u_l_y) / dist",
    ));
    loop_body.push(dsl::assign(
        "flux_rho_u_x",
        "flux_rho_u_x + diff_u_x",
    ));
    loop_body.push(dsl::assign(
        "flux_rho_u_y",
        "flux_rho_u_y + diff_u_y",
    ));

    loop_body.push(dsl::let_("f_rho_e_l", "(rho_e_l + p_l) * u_n_l"));
    loop_body.push(dsl::let_("f_rho_e_r", "(rho_e_r + p_r) * u_n_r"));
    loop_body.push(dsl::var(
        "flux_rho_e",
        "(a_plus * f_rho_e_l - a_minus * f_rho_e_r + a_prod * (rho_e_r - rho_e_l)) / denom",
    ));
    loop_body.push(dsl::assign(
        "flux_rho_e",
        "flux_rho_e + diff_u_x * u_face_x + diff_u_y * u_face_y",
    ));

    loop_body.push(dsl::assign_op(
        AssignOp::Add,
        "sum_rho",
        "flux_rho * area",
    ));
    loop_body.push(dsl::assign_op(
        AssignOp::Add,
        "sum_rho_u_x",
        "flux_rho_u_x * area",
    ));
    loop_body.push(dsl::assign_op(
        AssignOp::Add,
        "sum_rho_u_y",
        "flux_rho_u_y * area",
    ));
    loop_body.push(dsl::assign_op(
        AssignOp::Add,
        "sum_rho_e",
        "flux_rho_e * area",
    ));

    loop_body.push(dsl::let_("q_l", "u_l_x * u_l_x + u_l_y * u_l_y"));
    loop_body.push(dsl::let_(
        "dp_drho_l",
        &format!("0.5 * ({gamma} - 1.0) * q_l"),
    ));
    loop_body.push(dsl::let_(
        "dp_dru_l",
        &format!("-({gamma} - 1.0) * u_l_x"),
    ));
    loop_body.push(dsl::let_(
        "dp_drv_l",
        &format!("-({gamma} - 1.0) * u_l_y"),
    ));
    loop_body.push(dsl::let_("dp_dre_l", &format!("{gamma} - 1.0")));
    loop_body.push(dsl::let_("H_l", "(rho_e_l + p_l) * inv_rho_l"));

    loop_body.push(dsl::let_("q_r", "u_r_x * u_r_x + u_r_y * u_r_y"));
    loop_body.push(dsl::let_(
        "dp_drho_r",
        &format!("0.5 * ({gamma} - 1.0) * q_r"),
    ));
    loop_body.push(dsl::let_(
        "dp_dru_r",
        &format!("-({gamma} - 1.0) * u_r_x"),
    ));
    loop_body.push(dsl::let_(
        "dp_drv_r",
        &format!("-({gamma} - 1.0) * u_r_y"),
    ));
    loop_body.push(dsl::let_("dp_dre_r", &format!("{gamma} - 1.0")));
    loop_body.push(dsl::let_("H_r", "(rho_e_r + p_r) * inv_rho_r"));

    loop_body.push(dsl::let_("a_l", "a_plus / denom"));
    loop_body.push(dsl::let_("a_r", "-a_minus / denom"));
    loop_body.push(dsl::let_("a_prod_scaled", "a_prod / denom"));

    loop_body.push(dsl::var("jac_l_00", "-a_prod_scaled"));
    loop_body.push(dsl::var("jac_l_01", "a_l * normal.x"));
    loop_body.push(dsl::var("jac_l_02", "a_l * normal.y"));
    loop_body.push(dsl::var("jac_l_03", "0.0"));
    loop_body.push(dsl::var("jac_r_00", "a_prod_scaled"));
    loop_body.push(dsl::var("jac_r_01", "a_r * normal.x"));
    loop_body.push(dsl::var("jac_r_02", "a_r * normal.y"));
    loop_body.push(dsl::var("jac_r_03", "0.0"));

    loop_body.push(dsl::let_("A_l_10", "-u_l_x * u_n_l + dp_drho_l * normal.x"));
    loop_body.push(dsl::let_(
        "A_l_11",
        "u_n_l + u_l_x * normal.x + dp_dru_l * normal.x",
    ));
    loop_body.push(dsl::let_("A_l_12", "u_l_x * normal.y + dp_drv_l * normal.x"));
    loop_body.push(dsl::let_("A_l_13", "dp_dre_l * normal.x"));
    loop_body.push(dsl::let_("A_l_20", "-u_l_y * u_n_l + dp_drho_l * normal.y"));
    loop_body.push(dsl::let_(
        "A_l_21",
        "u_l_y * normal.x + dp_dru_l * normal.y",
    ));
    loop_body.push(dsl::let_(
        "A_l_22",
        "u_n_l + u_l_y * normal.y + dp_drv_l * normal.y",
    ));
    loop_body.push(dsl::let_("A_l_23", "dp_dre_l * normal.y"));
    loop_body.push(dsl::let_("A_l_30", "-H_l * u_n_l + dp_drho_l * u_n_l"));
    loop_body.push(dsl::let_("A_l_31", "H_l * normal.x + dp_dru_l * u_n_l"));
    loop_body.push(dsl::let_("A_l_32", "H_l * normal.y + dp_drv_l * u_n_l"));
    loop_body.push(dsl::let_("A_l_33", &format!("{gamma} * u_n_l")));

    loop_body.push(dsl::let_("A_r_10", "-u_r_x * u_n_r + dp_drho_r * normal.x"));
    loop_body.push(dsl::let_(
        "A_r_11",
        "u_n_r + u_r_x * normal.x + dp_dru_r * normal.x",
    ));
    loop_body.push(dsl::let_("A_r_12", "u_r_x * normal.y + dp_drv_r * normal.x"));
    loop_body.push(dsl::let_("A_r_13", "dp_dre_r * normal.x"));
    loop_body.push(dsl::let_("A_r_20", "-u_r_y * u_n_r + dp_drho_r * normal.y"));
    loop_body.push(dsl::let_(
        "A_r_21",
        "u_r_y * normal.x + dp_dru_r * normal.y",
    ));
    loop_body.push(dsl::let_(
        "A_r_22",
        "u_n_r + u_r_y * normal.y + dp_drv_r * normal.y",
    ));
    loop_body.push(dsl::let_("A_r_23", "dp_dre_r * normal.y"));
    loop_body.push(dsl::let_("A_r_30", "-H_r * u_n_r + dp_drho_r * u_n_r"));
    loop_body.push(dsl::let_("A_r_31", "H_r * normal.x + dp_dru_r * u_n_r"));
    loop_body.push(dsl::let_("A_r_32", "H_r * normal.y + dp_drv_r * u_n_r"));
    loop_body.push(dsl::let_("A_r_33", &format!("{gamma} * u_n_r")));

    loop_body.push(dsl::var("jac_l_10", "a_l * A_l_10"));
    loop_body.push(dsl::var("jac_l_11", "a_l * A_l_11 - a_prod_scaled"));
    loop_body.push(dsl::var("jac_l_12", "a_l * A_l_12"));
    loop_body.push(dsl::var("jac_l_13", "a_l * A_l_13"));
    loop_body.push(dsl::var("jac_r_10", "a_r * A_r_10"));
    loop_body.push(dsl::var("jac_r_11", "a_r * A_r_11 + a_prod_scaled"));
    loop_body.push(dsl::var("jac_r_12", "a_r * A_r_12"));
    loop_body.push(dsl::var("jac_r_13", "a_r * A_r_13"));

    loop_body.push(dsl::var("jac_l_20", "a_l * A_l_20"));
    loop_body.push(dsl::var("jac_l_21", "a_l * A_l_21"));
    loop_body.push(dsl::var("jac_l_22", "a_l * A_l_22 - a_prod_scaled"));
    loop_body.push(dsl::var("jac_l_23", "a_l * A_l_23"));
    loop_body.push(dsl::var("jac_r_20", "a_r * A_r_20"));
    loop_body.push(dsl::var("jac_r_21", "a_r * A_r_21"));
    loop_body.push(dsl::var("jac_r_22", "a_r * A_r_22 + a_prod_scaled"));
    loop_body.push(dsl::var("jac_r_23", "a_r * A_r_23"));

    loop_body.push(dsl::var("jac_l_30", "a_l * A_l_30"));
    loop_body.push(dsl::var("jac_l_31", "a_l * A_l_31"));
    loop_body.push(dsl::var("jac_l_32", "a_l * A_l_32"));
    loop_body.push(dsl::var("jac_l_33", "a_l * A_l_33 - a_prod_scaled"));
    loop_body.push(dsl::var("jac_r_30", "a_r * A_r_30"));
    loop_body.push(dsl::var("jac_r_31", "a_r * A_r_31"));
    loop_body.push(dsl::var("jac_r_32", "a_r * A_r_32"));
    loop_body.push(dsl::var("jac_r_33", "a_r * A_r_33 + a_prod_scaled"));

    loop_body.push(dsl::let_("mu_over_dist", "mu / dist"));
    loop_body.push(dsl::let_("du_lx_drho", "-u_l_x * inv_rho_l"));
    loop_body.push(dsl::let_("du_lx_dru", "inv_rho_l"));
    loop_body.push(dsl::let_("du_lx_drv", "0.0"));
    loop_body.push(dsl::let_("du_ly_drho", "-u_l_y * inv_rho_l"));
    loop_body.push(dsl::let_("du_ly_dru", "0.0"));
    loop_body.push(dsl::let_("du_ly_drv", "inv_rho_l"));

    loop_body.push(dsl::let_("du_rx_drho", "-u_r_x * inv_rho_r"));
    loop_body.push(dsl::let_("du_rx_dru", "inv_rho_r"));
    loop_body.push(dsl::let_("du_rx_drv", "0.0"));
    loop_body.push(dsl::let_("du_ry_drho", "-u_r_y * inv_rho_r"));
    loop_body.push(dsl::let_("du_ry_dru", "0.0"));
    loop_body.push(dsl::let_("du_ry_drv", "inv_rho_r"));

    loop_body.push(dsl::let_("d_diff_x_l_rho", "mu_over_dist * du_lx_drho"));
    loop_body.push(dsl::let_("d_diff_x_l_ru", "mu_over_dist * du_lx_dru"));
    loop_body.push(dsl::let_("d_diff_x_l_rv", "0.0"));
    loop_body.push(dsl::let_("d_diff_x_l_re", "0.0"));
    loop_body.push(dsl::let_("d_diff_y_l_rho", "mu_over_dist * du_ly_drho"));
    loop_body.push(dsl::let_("d_diff_y_l_ru", "0.0"));
    loop_body.push(dsl::let_("d_diff_y_l_rv", "mu_over_dist * du_ly_drv"));
    loop_body.push(dsl::let_("d_diff_y_l_re", "0.0"));

    loop_body.push(dsl::let_("d_diff_x_r_rho", "-mu_over_dist * du_rx_drho"));
    loop_body.push(dsl::let_("d_diff_x_r_ru", "-mu_over_dist * du_rx_dru"));
    loop_body.push(dsl::let_("d_diff_x_r_rv", "0.0"));
    loop_body.push(dsl::let_("d_diff_x_r_re", "0.0"));
    loop_body.push(dsl::let_("d_diff_y_r_rho", "-mu_over_dist * du_ry_drho"));
    loop_body.push(dsl::let_("d_diff_y_r_ru", "0.0"));
    loop_body.push(dsl::let_("d_diff_y_r_rv", "-mu_over_dist * du_ry_drv"));
    loop_body.push(dsl::let_("d_diff_y_r_re", "0.0"));

    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_10", "d_diff_x_l_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_11", "d_diff_x_l_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_12", "d_diff_x_l_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_13", "d_diff_x_l_re"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_20", "d_diff_y_l_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_21", "d_diff_y_l_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_22", "d_diff_y_l_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_23", "d_diff_y_l_re"));

    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_10", "d_diff_x_r_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_11", "d_diff_x_r_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_12", "d_diff_x_r_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_13", "d_diff_x_r_re"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_20", "d_diff_y_r_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_21", "d_diff_y_r_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_22", "d_diff_y_r_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_23", "d_diff_y_r_re"));

    loop_body.push(dsl::let_("du_face_x_l_rho", "0.5 * du_lx_drho"));
    loop_body.push(dsl::let_("du_face_x_l_ru", "0.5 * du_lx_dru"));
    loop_body.push(dsl::let_("du_face_x_l_rv", "0.0"));
    loop_body.push(dsl::let_("du_face_x_l_re", "0.0"));
    loop_body.push(dsl::let_("du_face_y_l_rho", "0.5 * du_ly_drho"));
    loop_body.push(dsl::let_("du_face_y_l_ru", "0.0"));
    loop_body.push(dsl::let_("du_face_y_l_rv", "0.5 * du_ly_drv"));
    loop_body.push(dsl::let_("du_face_y_l_re", "0.0"));

    loop_body.push(dsl::let_("du_face_x_r_rho", "0.5 * du_rx_drho"));
    loop_body.push(dsl::let_("du_face_x_r_ru", "0.5 * du_rx_dru"));
    loop_body.push(dsl::let_("du_face_x_r_rv", "0.0"));
    loop_body.push(dsl::let_("du_face_x_r_re", "0.0"));
    loop_body.push(dsl::let_("du_face_y_r_rho", "0.5 * du_ry_drho"));
    loop_body.push(dsl::let_("du_face_y_r_ru", "0.0"));
    loop_body.push(dsl::let_("du_face_y_r_rv", "0.5 * du_ry_drv"));
    loop_body.push(dsl::let_("du_face_y_r_re", "0.0"));

    loop_body.push(dsl::let_(
        "d_e_visc_l_rho",
        "d_diff_x_l_rho * u_face_x + diff_u_x * du_face_x_l_rho + d_diff_y_l_rho * u_face_y + diff_u_y * du_face_y_l_rho",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_l_ru",
        "d_diff_x_l_ru * u_face_x + diff_u_x * du_face_x_l_ru + d_diff_y_l_ru * u_face_y + diff_u_y * du_face_y_l_ru",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_l_rv",
        "d_diff_x_l_rv * u_face_x + diff_u_x * du_face_x_l_rv + d_diff_y_l_rv * u_face_y + diff_u_y * du_face_y_l_rv",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_l_re",
        "d_diff_x_l_re * u_face_x + diff_u_x * du_face_x_l_re + d_diff_y_l_re * u_face_y + diff_u_y * du_face_y_l_re",
    ));

    loop_body.push(dsl::let_(
        "d_e_visc_r_rho",
        "d_diff_x_r_rho * u_face_x + diff_u_x * du_face_x_r_rho + d_diff_y_r_rho * u_face_y + diff_u_y * du_face_y_r_rho",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_r_ru",
        "d_diff_x_r_ru * u_face_x + diff_u_x * du_face_x_r_ru + d_diff_y_r_ru * u_face_y + diff_u_y * du_face_y_r_ru",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_r_rv",
        "d_diff_x_r_rv * u_face_x + diff_u_x * du_face_x_r_rv + d_diff_y_r_rv * u_face_y + diff_u_y * du_face_y_r_rv",
    ));
    loop_body.push(dsl::let_(
        "d_e_visc_r_re",
        "d_diff_x_r_re * u_face_x + diff_u_x * du_face_x_r_re + d_diff_y_r_re * u_face_y + diff_u_y * du_face_y_r_re",
    ));

    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_30", "d_e_visc_l_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_31", "d_e_visc_l_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_32", "d_e_visc_l_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_l_33", "d_e_visc_l_re"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_30", "d_e_visc_r_rho"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_31", "d_e_visc_r_ru"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_32", "d_e_visc_r_rv"));
    loop_body.push(dsl::assign_op(AssignOp::Add, "jac_r_33", "d_e_visc_r_re"));

    let mut interior_matrix_stmts = vec![
        dsl::let_("scalar_mat_idx", "cell_face_matrix_indices[face_offset]"),
        dsl::var("neighbor_rank", "0u"),
        dsl::if_block(
            "scalar_mat_idx != 4294967295u",
            dsl::block(vec![dsl::assign("neighbor_rank", "scalar_mat_idx - scalar_offset")]),
            Some(dsl::block(vec![dsl::assign(
                "neighbor_rank",
                "scalar_mat_idx - scalar_offset",
            )])),
        ),
        dsl::let_("base_0", "start_row_0 + 4u * neighbor_rank"),
        dsl::let_("base_1", "start_row_1 + 4u * neighbor_rank"),
        dsl::let_("base_2", "start_row_2 + 4u * neighbor_rank"),
        dsl::let_("base_3", "start_row_3 + 4u * neighbor_rank"),
    ];

    interior_matrix_stmts.push(dsl::if_block(
        "scheme_id != 0u",
        {
            let mut ho_block = Vec::new();
            let (rho_stmts, rho_vars) = scalar_reconstruction(
                "rho",
                "scheme_id",
                "flux_adv",
                "rho_l",
                "rho_r",
                "grad_rho[idx]",
                "grad_rho[other_idx]",
                "center",
                "center_r",
                "f_center",
            );
            ho_block.extend(rho_stmts);
            let (ru_stmts, ru_vars) = scalar_reconstruction(
                "ru",
                "scheme_id",
                "flux_adv",
                "rho_u_l.x",
                "rho_u_r.x",
                "grad_rho_u_x[idx]",
                "grad_rho_u_x[other_idx]",
                "center",
                "center_r",
                "f_center",
            );
            ho_block.extend(ru_stmts);
            let (rv_stmts, rv_vars) = scalar_reconstruction(
                "rv",
                "scheme_id",
                "flux_adv",
                "rho_u_l.y",
                "rho_u_r.y",
                "grad_rho_u_y[idx]",
                "grad_rho_u_y[other_idx]",
                "center",
                "center_r",
                "f_center",
            );
            ho_block.extend(rv_stmts);
            let (re_stmts, re_vars) = scalar_reconstruction(
                "re",
                "scheme_id",
                "flux_adv",
                "rho_e_l",
                "rho_e_r",
                "grad_rho_e[idx]",
                "grad_rho_e[other_idx]",
                "center",
                "center_r",
                "f_center",
            );
            ho_block.extend(re_stmts);
            ho_block.push(dsl::let_(
                "correction_rho",
                &format!("flux_adv * ({} - {})", rho_vars.phi_ho, rho_vars.phi_upwind),
            ));
            ho_block.push(dsl::let_(
                "correction_rho_u_x",
                &format!("flux_adv * ({} - {})", ru_vars.phi_ho, ru_vars.phi_upwind),
            ));
            ho_block.push(dsl::let_(
                "correction_rho_u_y",
                &format!("flux_adv * ({} - {})", rv_vars.phi_ho, rv_vars.phi_upwind),
            ));
            ho_block.push(dsl::let_(
                "correction_rho_e",
                &format!("flux_adv * ({} - {})", re_vars.phi_ho, re_vars.phi_upwind),
            ));
            ho_block.push(dsl::assign_op(AssignOp::Add, "sum_rho", "correction_rho"));
            ho_block.push(dsl::assign_op(
                AssignOp::Add,
                "sum_rho_u_x",
                "correction_rho_u_x",
            ));
            ho_block.push(dsl::assign_op(
                AssignOp::Add,
                "sum_rho_u_y",
                "correction_rho_u_y",
            ));
            ho_block.push(dsl::assign_op(AssignOp::Add, "sum_rho_e", "correction_rho_e"));
            dsl::block(ho_block)
        },
        None,
    ));

    interior_matrix_stmts.extend(vec![
        dsl::assign("matrix_values[base_0 + 0u]", "jac_r_00 * area"),
        dsl::assign("matrix_values[base_0 + 1u]", "jac_r_01 * area"),
        dsl::assign("matrix_values[base_0 + 2u]", "jac_r_02 * area"),
        dsl::assign("matrix_values[base_0 + 3u]", "jac_r_03 * area"),
        dsl::assign("matrix_values[base_1 + 0u]", "jac_r_10 * area"),
        dsl::assign("matrix_values[base_1 + 1u]", "jac_r_11 * area"),
        dsl::assign("matrix_values[base_1 + 2u]", "jac_r_12 * area"),
        dsl::assign("matrix_values[base_1 + 3u]", "jac_r_13 * area"),
        dsl::assign("matrix_values[base_2 + 0u]", "jac_r_20 * area"),
        dsl::assign("matrix_values[base_2 + 1u]", "jac_r_21 * area"),
        dsl::assign("matrix_values[base_2 + 2u]", "jac_r_22 * area"),
        dsl::assign("matrix_values[base_2 + 3u]", "jac_r_23 * area"),
        dsl::assign("matrix_values[base_3 + 0u]", "jac_r_30 * area"),
        dsl::assign("matrix_values[base_3 + 1u]", "jac_r_31 * area"),
        dsl::assign("matrix_values[base_3 + 2u]", "jac_r_32 * area"),
        dsl::assign("matrix_values[base_3 + 3u]", "jac_r_33 * area"),
        dsl::assign_op(AssignOp::Add, "diag_00", "jac_l_00 * area"),
        dsl::assign_op(AssignOp::Add, "diag_01", "jac_l_01 * area"),
        dsl::assign_op(AssignOp::Add, "diag_02", "jac_l_02 * area"),
        dsl::assign_op(AssignOp::Add, "diag_03", "jac_l_03 * area"),
        dsl::assign_op(AssignOp::Add, "diag_10", "jac_l_10 * area"),
        dsl::assign_op(AssignOp::Add, "diag_11", "jac_l_11 * area"),
        dsl::assign_op(AssignOp::Add, "diag_12", "jac_l_12 * area"),
        dsl::assign_op(AssignOp::Add, "diag_13", "jac_l_13 * area"),
        dsl::assign_op(AssignOp::Add, "diag_20", "jac_l_20 * area"),
        dsl::assign_op(AssignOp::Add, "diag_21", "jac_l_21 * area"),
        dsl::assign_op(AssignOp::Add, "diag_22", "jac_l_22 * area"),
        dsl::assign_op(AssignOp::Add, "diag_23", "jac_l_23 * area"),
        dsl::assign_op(AssignOp::Add, "diag_30", "jac_l_30 * area"),
        dsl::assign_op(AssignOp::Add, "diag_31", "jac_l_31 * area"),
        dsl::assign_op(AssignOp::Add, "diag_32", "jac_l_32 * area"),
        dsl::assign_op(AssignOp::Add, "diag_33", "jac_l_33 * area"),
    ]);

    let interior_matrix = dsl::block(interior_matrix_stmts);

    let boundary_matrix = {
        let mut body = Vec::new();
        body.push(dsl::var("eff_00", "jac_l_00 + jac_r_00"));
        body.push(dsl::var("eff_01", "jac_l_01 + jac_r_01"));
        body.push(dsl::var("eff_02", "jac_l_02 + jac_r_02"));
        body.push(dsl::var("eff_03", "jac_l_03 + jac_r_03"));
        body.push(dsl::var("eff_10", "jac_l_10 + jac_r_10"));
        body.push(dsl::var("eff_11", "jac_l_11 + jac_r_11"));
        body.push(dsl::var("eff_12", "jac_l_12 + jac_r_12"));
        body.push(dsl::var("eff_13", "jac_l_13 + jac_r_13"));
        body.push(dsl::var("eff_20", "jac_l_20 + jac_r_20"));
        body.push(dsl::var("eff_21", "jac_l_21 + jac_r_21"));
        body.push(dsl::var("eff_22", "jac_l_22 + jac_r_22"));
        body.push(dsl::var("eff_23", "jac_l_23 + jac_r_23"));
        body.push(dsl::var("eff_30", "jac_l_30 + jac_r_30"));
        body.push(dsl::var("eff_31", "jac_l_31 + jac_r_31"));
        body.push(dsl::var("eff_32", "jac_l_32 + jac_r_32"));
        body.push(dsl::var("eff_33", "jac_l_33 + jac_r_33"));

        let inlet_block = dsl::block(vec![
            dsl::assign(
                "eff_00",
                "jac_l_00 + jac_r_00 + jac_r_01 * constants.inlet_velocity",
            ),
            dsl::assign("eff_01", "jac_l_01"),
            dsl::assign("eff_02", "jac_l_02"),
            dsl::assign("eff_03", "jac_l_03 + jac_r_03"),
            dsl::assign(
                "eff_10",
                "jac_l_10 + jac_r_10 + jac_r_11 * constants.inlet_velocity",
            ),
            dsl::assign("eff_11", "jac_l_11"),
            dsl::assign("eff_12", "jac_l_12"),
            dsl::assign("eff_13", "jac_l_13 + jac_r_13"),
            dsl::assign(
                "eff_20",
                "jac_l_20 + jac_r_20 + jac_r_21 * constants.inlet_velocity",
            ),
            dsl::assign("eff_21", "jac_l_21"),
            dsl::assign("eff_22", "jac_l_22"),
            dsl::assign("eff_23", "jac_l_23 + jac_r_23"),
            dsl::assign(
                "eff_30",
                "jac_l_30 + jac_r_30 + jac_r_31 * constants.inlet_velocity",
            ),
            dsl::assign("eff_31", "jac_l_31"),
            dsl::assign("eff_32", "jac_l_32"),
            dsl::assign("eff_33", "jac_l_33 + jac_r_33"),
        ]);

        let wall_block = dsl::block(vec![
            dsl::assign("eff_00", "jac_l_00 + jac_r_00"),
            dsl::assign("eff_01", "jac_l_01 - jac_r_01"),
            dsl::assign("eff_02", "jac_l_02 - jac_r_02"),
            dsl::assign("eff_03", "jac_l_03 + jac_r_03"),
            dsl::assign("eff_10", "jac_l_10 + jac_r_10"),
            dsl::assign("eff_11", "jac_l_11 - jac_r_11"),
            dsl::assign("eff_12", "jac_l_12 - jac_r_12"),
            dsl::assign("eff_13", "jac_l_13 + jac_r_13"),
            dsl::assign("eff_20", "jac_l_20 + jac_r_20"),
            dsl::assign("eff_21", "jac_l_21 - jac_r_21"),
            dsl::assign("eff_22", "jac_l_22 - jac_r_22"),
            dsl::assign("eff_23", "jac_l_23 + jac_r_23"),
            dsl::assign("eff_30", "jac_l_30 + jac_r_30"),
            dsl::assign("eff_31", "jac_l_31 - jac_r_31"),
            dsl::assign("eff_32", "jac_l_32 - jac_r_32"),
            dsl::assign("eff_33", "jac_l_33 + jac_r_33"),
        ]);

        body.push(dsl::if_block(
            "boundary_type == 1u",
            inlet_block,
            Some(dsl::block(vec![dsl::if_block(
                "boundary_type == 3u",
                wall_block,
                None,
            )])),
        ));

        body.push(dsl::assign_op(AssignOp::Add, "diag_00", "eff_00 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_01", "eff_01 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_02", "eff_02 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_03", "eff_03 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_10", "eff_10 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_11", "eff_11 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_12", "eff_12 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_13", "eff_13 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_20", "eff_20 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_21", "eff_21 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_22", "eff_22 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_23", "eff_23 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_30", "eff_30 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_31", "eff_31 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_32", "eff_32 * area"));
        body.push(dsl::assign_op(AssignOp::Add, "diag_33", "eff_33 * area"));
        dsl::block(body)
    };

    loop_body.push(dsl::if_block(
        "!is_boundary",
        interior_matrix,
        Some(boundary_matrix),
    ));

    stmts.push(dsl::for_loop(
        dsl::for_init_var("face_offset", "start"),
        "face_offset < end",
        dsl::for_step_increment("face_offset"),
        dsl::block(loop_body),
    ));

    stmts.push(dsl::var(
        "rhs_rho",
        "rhs_time_rho - coeff_time * rho - sum_rho",
    ));
    stmts.push(dsl::var(
        "rhs_rho_u_x",
        "rhs_time_rho_u_x - coeff_time * rho_u.x - sum_rho_u_x",
    ));
    stmts.push(dsl::var(
        "rhs_rho_u_y",
        "rhs_time_rho_u_y - coeff_time * rho_u.y - sum_rho_u_y",
    ));
    stmts.push(dsl::var(
        "rhs_rho_e",
        "rhs_time_rho_e - coeff_time * rho_e - sum_rho_e",
    ));

    stmts.push(dsl::assign_op(AssignOp::Add, "diag_00", "coeff_time"));
    stmts.push(dsl::assign_op(AssignOp::Add, "diag_11", "coeff_time"));
    stmts.push(dsl::assign_op(AssignOp::Add, "diag_22", "coeff_time"));
    stmts.push(dsl::assign_op(AssignOp::Add, "diag_33", "coeff_time"));

    stmts.push(dsl::let_("scalar_diag_idx", "diagonal_indices[idx]"));
    stmts.push(dsl::let_("diag_rank", "scalar_diag_idx - scalar_offset"));
    stmts.push(dsl::let_("diag_base_0", "start_row_0 + 4u * diag_rank"));
    stmts.push(dsl::let_("diag_base_1", "start_row_1 + 4u * diag_rank"));
    stmts.push(dsl::let_("diag_base_2", "start_row_2 + 4u * diag_rank"));
    stmts.push(dsl::let_("diag_base_3", "start_row_3 + 4u * diag_rank"));

    stmts.push(dsl::assign("matrix_values[diag_base_0 + 0u]", "diag_00"));
    stmts.push(dsl::assign("matrix_values[diag_base_0 + 1u]", "diag_01"));
    stmts.push(dsl::assign("matrix_values[diag_base_0 + 2u]", "diag_02"));
    stmts.push(dsl::assign("matrix_values[diag_base_0 + 3u]", "diag_03"));
    stmts.push(dsl::assign("matrix_values[diag_base_1 + 0u]", "diag_10"));
    stmts.push(dsl::assign("matrix_values[diag_base_1 + 1u]", "diag_11"));
    stmts.push(dsl::assign("matrix_values[diag_base_1 + 2u]", "diag_12"));
    stmts.push(dsl::assign("matrix_values[diag_base_1 + 3u]", "diag_13"));
    stmts.push(dsl::assign("matrix_values[diag_base_2 + 0u]", "diag_20"));
    stmts.push(dsl::assign("matrix_values[diag_base_2 + 1u]", "diag_21"));
    stmts.push(dsl::assign("matrix_values[diag_base_2 + 2u]", "diag_22"));
    stmts.push(dsl::assign("matrix_values[diag_base_2 + 3u]", "diag_23"));
    stmts.push(dsl::assign("matrix_values[diag_base_3 + 0u]", "diag_30"));
    stmts.push(dsl::assign("matrix_values[diag_base_3 + 1u]", "diag_31"));
    stmts.push(dsl::assign("matrix_values[diag_base_3 + 2u]", "diag_32"));
    stmts.push(dsl::assign("matrix_values[diag_base_3 + 3u]", "diag_33"));

    stmts.push(dsl::assign("rhs[4u * idx + 0u]", "rhs_rho"));
    stmts.push(dsl::assign("rhs[4u * idx + 1u]", "rhs_rho_u_x"));
    stmts.push(dsl::assign("rhs[4u * idx + 2u]", "rhs_rho_u_y"));
    stmts.push(dsl::assign("rhs[4u * idx + 3u]", "rhs_rho_e"));

    Block::new(stmts)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::solver::model::compressible_model;

    #[test]
    fn compressible_assembly_codegen_emits_bindings() {
        let model = compressible_model();
        let fields = model.fields.compressible().expect("compressible fields");
        let wgsl = generate_compressible_assembly_wgsl(&model.state_layout, fields);
        assert!(wgsl.contains("matrix_values"));
        assert!(wgsl.contains("rhs"));
        assert!(wgsl.contains("scalar_row_offsets"));
        assert!(wgsl.contains("state: array<f32>"));
        assert!(wgsl.contains("sum_rho"));
        assert!(wgsl.contains("rhs_time_rho"));
        assert!(wgsl.contains("jac_l_00"));
    }
}
