pub mod coeff_expr;
pub mod coupled_assembly;
pub mod dsl;
pub mod flux_kt;
pub mod flux_rhie_chow;
pub mod generic_coupled_kernels;
pub mod incompressible_fields;
pub mod ir;
pub mod kt_gradients;
pub mod plan;
pub mod prepare_coupled;
pub mod primitive_expr;
pub mod pressure_assembly;
pub mod reconstruction;
pub mod state_access;
pub mod unified_assembly;
pub mod update_fields_from_coupled;
pub mod wgsl;
pub mod wgsl_ast;
pub mod wgsl_dsl;

pub use coupled_assembly::generate_coupled_assembly_wgsl;
pub use flux_kt::generate_flux_kt_wgsl;
pub use flux_rhie_chow::generate_flux_rhie_chow_wgsl;
pub use incompressible_fields::CodegenIncompressibleMomentumFields;
pub use ir::{lower_system, DiscreteEquation, DiscreteOp, DiscreteOpKind, DiscreteSystem};
pub use kt_gradients::generate_kt_gradients_wgsl;
pub use prepare_coupled::generate_prepare_coupled_wgsl;
pub use pressure_assembly::generate_pressure_assembly_wgsl;
pub use state_access::{state_component_expr, state_scalar_expr, state_vec2_expr};
pub use update_fields_from_coupled::generate_update_fields_from_coupled_wgsl;
pub use wgsl::{generate_wgsl, generate_wgsl_library};
