pub mod ei;
pub mod method_ei;
pub mod coupled_assembly;
pub mod dsl;
pub mod emit;
pub mod flux_rhie_chow;
pub mod generic_coupled_kernels;
pub mod ir;
pub mod plan;
pub mod prepare_coupled;
pub mod pressure_assembly;
pub mod reconstruction;
pub mod state_access;
pub mod unified_assembly;
pub mod update_fields_from_coupled;
pub mod wgsl;
pub mod wgsl_ast;
pub mod wgsl_dsl;

pub use ei::apply::generate_ei_apply_wgsl;
pub use ei::assembly::generate_ei_assembly_wgsl;
pub use ei::explicit_update::generate_ei_explicit_update_wgsl;
pub use ei::flux_kt::generate_ei_flux_kt_wgsl;
pub use ei::gradients::generate_ei_gradients_wgsl;
pub use ei::update::generate_ei_update_wgsl;
pub use coupled_assembly::generate_coupled_assembly_wgsl;
pub use emit::emit_coupled_assembly_codegen_wgsl;
pub use emit::emit_coupled_assembly_codegen_wgsl_with_schemes;
pub use emit::emit_flux_rhie_chow_codegen_wgsl;
pub use emit::emit_system_main_wgsl;
pub use emit::emit_system_main_wgsl_with_schemes;
pub use emit::emit_model_kernel_wgsl;
pub use emit::emit_model_kernel_wgsl_with_schemes;
pub use emit::emit_model_kernels_wgsl;
pub use emit::emit_prepare_coupled_codegen_wgsl;
pub use emit::emit_pressure_assembly_codegen_wgsl;
pub use emit::emit_update_fields_from_coupled_codegen_wgsl;
pub use emit::write_wgsl_file;
pub use flux_rhie_chow::generate_flux_rhie_chow_wgsl;
pub use ir::{lower_system, DiscreteEquation, DiscreteOp, DiscreteOpKind, DiscreteSystem};
pub use prepare_coupled::generate_prepare_coupled_wgsl;
pub use pressure_assembly::generate_pressure_assembly_wgsl;
pub use state_access::{state_component_expr, state_scalar_expr, state_vec2_expr};
pub use update_fields_from_coupled::generate_update_fields_from_coupled_wgsl;
pub use wgsl::{generate_wgsl, generate_wgsl_library};
pub mod coeff_expr;
